linters:
  enable:
    - asasalint
    - asciicheck
    - bodyclose
    - dogsled
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - inamedparam
    - intrange
    - ireturn
    - makezero
    - mirror
    - misspell
    - noctx
    - nolintlint
    - perfsprint
    - predeclared
    - reassign
    - revive
    - testifylint
    - unconvert
    - usestdlibvars
    - zerologlint
    - rowserrcheck
    - sqlclosecheck
    - tagliatelle
    - tenv
    - thelper
    - tparallel
    - testableexamples

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - opinionated
      - performance
    disabled-tags:
      - experimental

  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake

  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib

      # no concrete types are exposed for huma.API
      - github.com\/danielgtaylor\/huma\/v2\.API

  revive:
    ignore-generated-header: true
    severity: warning
    confidence: 0.8
    rules:
      - name: atomic
        severity: error
      - name: bare-return
        severity: error
      - name: call-to-gc
      - name: cyclomatic
        severity: warning
        arguments: [10]
      - name: cognitive-complexity
        severity: warning
        arguments: [15]
      - name: defer
        severity: error
      - name: early-return
      - name: flag-parameter
      - name: get-return
      - name: identical-branches
      - name: if-return
      - name: indent-error-flow
      - name: import-shadowing
      # Catch mutation bugs
      - name: modifies-parameter
      - name: modifies-value-receiver
      # Typical range gotchas
      - name: range-val-in-closure
      - name: range-val-address
      - name: string-of-int
      - name: superfluous-else
      - name: unconditional-recursion
      - name: unexported-naming
      - name: unnecessary-stmt
      - name: waitgroup-by-value

  govet:
    enable:
      - fieldalignment # Useful to reduce memory usage

  gosec:
    excludes:
      # Disable file permission checks. These are way too restrictive and would
      # only allow creating files that can be accessed by only the creator.
      - G301
      - G302
      - G306
      - G307

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - bodyclose # Due to https://github.com/timakin/bodyclose/issues/59
    - path: '(.+)_integration_test\.go'
      linters:
        - tparallel # Many integration tests requires serialization

    # Exempt route registration from complexity checks as they are typically
    # multiple routes bundled in one function.
    - text: 'function \(.*Route\)\.Register.* has (cognitive|cyclomatic) complexity'
      linters:
        - revive

    # Exempt integration tests from complexity checks as they will be huge due to
    # having multiple levels of subtests.
    - text: "function Test.*Integration has (cognitive|cyclomatic) complexity"
      linters:
        - revive

  exclude-files:
    - internal/pkg/dbmodels
