services:
  parkserver:
    image: localhost/parkserver
    build:
      context: .
      dockerfile: ./Containerfile
    ports:
      - "8080:8080"
      - "6060:6060"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "/parkserver", "check-health"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      INSECURE: true
    networks:
      - backend

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgres/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  database:
