services:
  # Override with air version of parkserver
  parkserver:
    image: localhost/parkserver-air
    build:
      context: .
      dockerfile: ./Containerfile.air
    volumes:
      - ./:/src # Mount codebase to /src
    security_opt:
      - label=disable
