services:
  parkserver-air:
    build:
      context: .
      dockerfile: ./Containerfile.air
    ports:
      - 8080:8080 # API
    volumes:
      - ./:/src # Mount codebase to /src
    security_opt:
      - "label=disable"
