-- Car details
CREATE TABLE IF NOT EXISTS Car (
  CarId SERIAL PRIMARY KEY NOT NULL,
  UserUUID UUID UNIQUE NOT NULL REFERENCES Users(UserUUID),
  CarUUID UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  LicensePlate TEXT NOT NULL,
  Make TEXT NOT NULL,
  Model TEXT NOT NULL,
  Color TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS CarUUIDs ON Car(CarUUID);