-- Auth details
CREATE TABLE IF NOT EXISTS Auth (
  AuthID SERIAL PRIMARY KEY NOT NULL,
  AuthUUID UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
  Email TEXT NOT NULL,
  PasswordHash TEXT NOT NULL
);

-- User details
CREATE TABLE IF NOT EXISTS Users (
  UserID SERIAL PRIMARY KEY NOT NULL,
  AuthUUID UUID UNIQUE NOT NULL REFERENCES Auth(AuthUUID),
  UserUUID UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
  FullName TEXT NOT NULL,
  Email TEXT NOT NULL,
  IsVerified BOOLEAN NOT NULL DEFAULT false,
  AddedAt TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS UserUUIDs ON Users (UserUUID);
CREATE UNIQUE INDEX IF NOT EXISTS AuthUUIDs ON Auth (AuthUUID);
