// Code generated by modelgen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import (
	"database/sql"
	"database/sql/driver"

	"github.com/ParkWithEase/parkeasy/backend/internal/pkg/dbtype"
	"github.com/google/uuid"
	"github.com/govalues/decimal"
	"github.com/stephenafamo/bob"
)

// Make sure the type Auth runs hooks after queries
var _ bob.HookableType = &Auth{}

// Make sure the type Booking runs hooks after queries
var _ bob.HookableType = &Booking{}

// Make sure the type Car runs hooks after queries
var _ bob.HookableType = &Car{}

// Make sure the type Parkingspot runs hooks after queries
var _ bob.HookableType = &Parkingspot{}

// Make sure the type Preferencespot runs hooks after queries
var _ bob.HookableType = &Preferencespot{}

// Make sure the type Resettoken runs hooks after queries
var _ bob.HookableType = &Resettoken{}

// Make sure the type Session runs hooks after queries
var _ bob.HookableType = &Session{}

// Make sure the type Timeunit runs hooks after queries
var _ bob.HookableType = &Timeunit{}

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &User{}

// Make sure the type uuid.UUID satisfies database/sql.Scanner
var _ sql.Scanner = (*uuid.UUID)(nil)

// Make sure the type uuid.UUID satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(uuid.UUID)

// Make sure the type decimal.Decimal satisfies database/sql.Scanner
var _ sql.Scanner = (*decimal.Decimal)(nil)

// Make sure the type decimal.Decimal satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(decimal.Decimal)

// Make sure the type dbtype.Tstzrange satisfies database/sql.Scanner
var _ sql.Scanner = (*dbtype.Tstzrange)(nil)

// Make sure the type dbtype.Tstzrange satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(dbtype.Tstzrange)
