// Code generated by modelgen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/im"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// Preferencespot is an object representing the database table.
type Preferencespot struct {
	Userid        int64 `db:"userid,pk" `
	Parkingspotid int64 `db:"parkingspotid,pk" `

	R preferencespotR `db:"-" `
}

// PreferencespotSlice is an alias for a slice of pointers to Preferencespot.
// This should almost always be used instead of []*Preferencespot.
type PreferencespotSlice []*Preferencespot

// Preferencespots contains methods to work with the preferencespots table
var Preferencespots = psql.NewTablex[*Preferencespot, PreferencespotSlice, *PreferencespotSetter]("", "preferencespots")

// PreferencespotsQuery is a query on the preferencespots table
type PreferencespotsQuery = *psql.ViewQuery[*Preferencespot, PreferencespotSlice]

// PreferencespotsStmt is a prepared statment on preferencespots
type PreferencespotsStmt = bob.QueryStmt[*Preferencespot, PreferencespotSlice]

// preferencespotR is where relationships are stored.
type preferencespotR struct {
	ParkingspotidParkingspot *Parkingspot // preferencespots.preferencespots_parkingspotid_fkey
	UseridUser               *User        // preferencespots.preferencespots_userid_fkey
}

// PreferencespotSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type PreferencespotSetter struct {
	Userid        omit.Val[int64] `db:"userid,pk" `
	Parkingspotid omit.Val[int64] `db:"parkingspotid,pk" `
}

func (s PreferencespotSetter) SetColumns() []string {
	vals := make([]string, 0, 2)
	if !s.Userid.IsUnset() {
		vals = append(vals, "userid")
	}

	if !s.Parkingspotid.IsUnset() {
		vals = append(vals, "parkingspotid")
	}

	return vals
}

func (s PreferencespotSetter) Overwrite(t *Preferencespot) {
	if !s.Userid.IsUnset() {
		t.Userid, _ = s.Userid.Get()
	}
	if !s.Parkingspotid.IsUnset() {
		t.Parkingspotid, _ = s.Parkingspotid.Get()
	}
}

func (s PreferencespotSetter) InsertMod() bob.Mod[*dialect.InsertQuery] {
	vals := make([]bob.Expression, 2)
	if s.Userid.IsUnset() {
		vals[0] = psql.Raw("DEFAULT")
	} else {
		vals[0] = psql.Arg(s.Userid)
	}

	if s.Parkingspotid.IsUnset() {
		vals[1] = psql.Raw("DEFAULT")
	} else {
		vals[1] = psql.Arg(s.Parkingspotid)
	}

	return im.Values(vals...)
}

func (s PreferencespotSetter) Apply(q *dialect.UpdateQuery) {
	um.Set(s.Expressions()...).Apply(q)
}

func (s PreferencespotSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 2)

	if !s.Userid.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "userid")...),
			psql.Arg(s.Userid),
		}})
	}

	if !s.Parkingspotid.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "parkingspotid")...),
			psql.Arg(s.Parkingspotid),
		}})
	}

	return exprs
}

type preferencespotColumnNames struct {
	Userid        string
	Parkingspotid string
}

var PreferencespotColumns = buildPreferencespotColumns("preferencespots")

type preferencespotColumns struct {
	tableAlias    string
	Userid        psql.Expression
	Parkingspotid psql.Expression
}

func (c preferencespotColumns) Alias() string {
	return c.tableAlias
}

func (preferencespotColumns) AliasedAs(alias string) preferencespotColumns {
	return buildPreferencespotColumns(alias)
}

func buildPreferencespotColumns(alias string) preferencespotColumns {
	return preferencespotColumns{
		tableAlias:    alias,
		Userid:        psql.Quote(alias, "userid"),
		Parkingspotid: psql.Quote(alias, "parkingspotid"),
	}
}

type preferencespotWhere[Q psql.Filterable] struct {
	Userid        psql.WhereMod[Q, int64]
	Parkingspotid psql.WhereMod[Q, int64]
}

func (preferencespotWhere[Q]) AliasedAs(alias string) preferencespotWhere[Q] {
	return buildPreferencespotWhere[Q](buildPreferencespotColumns(alias))
}

func buildPreferencespotWhere[Q psql.Filterable](cols preferencespotColumns) preferencespotWhere[Q] {
	return preferencespotWhere[Q]{
		Userid:        psql.Where[Q, int64](cols.Userid),
		Parkingspotid: psql.Where[Q, int64](cols.Parkingspotid),
	}
}

type preferencespotJoins[Q dialect.Joinable] struct {
	typ                      string
	ParkingspotidParkingspot func(context.Context) modAs[Q, parkingspotColumns]
	UseridUser               func(context.Context) modAs[Q, userColumns]
}

func (j preferencespotJoins[Q]) aliasedAs(alias string) preferencespotJoins[Q] {
	return buildPreferencespotJoins[Q](buildPreferencespotColumns(alias), j.typ)
}

func buildPreferencespotJoins[Q dialect.Joinable](cols preferencespotColumns, typ string) preferencespotJoins[Q] {
	return preferencespotJoins[Q]{
		typ:                      typ,
		ParkingspotidParkingspot: preferencespotsJoinParkingspotidParkingspot[Q](cols, typ),
		UseridUser:               preferencespotsJoinUseridUser[Q](cols, typ),
	}
}

// FindPreferencespot retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindPreferencespot(ctx context.Context, exec bob.Executor, UseridPK int64, ParkingspotidPK int64, cols ...string) (*Preferencespot, error) {
	if len(cols) == 0 {
		return Preferencespots.Query(
			ctx, exec,
			SelectWhere.Preferencespots.Userid.EQ(UseridPK),
			SelectWhere.Preferencespots.Parkingspotid.EQ(ParkingspotidPK),
		).One()
	}

	return Preferencespots.Query(
		ctx, exec,
		SelectWhere.Preferencespots.Userid.EQ(UseridPK),
		SelectWhere.Preferencespots.Parkingspotid.EQ(ParkingspotidPK),
		sm.Columns(Preferencespots.Columns().Only(cols...)),
	).One()
}

// PreferencespotExists checks the presence of a single record by primary key
func PreferencespotExists(ctx context.Context, exec bob.Executor, UseridPK int64, ParkingspotidPK int64) (bool, error) {
	return Preferencespots.Query(
		ctx, exec,
		SelectWhere.Preferencespots.Userid.EQ(UseridPK),
		SelectWhere.Preferencespots.Parkingspotid.EQ(ParkingspotidPK),
	).Exists()
}

// PrimaryKeyVals returns the primary key values of the Preferencespot
func (o *Preferencespot) PrimaryKeyVals() bob.Expression {
	return psql.ArgGroup(
		o.Userid,
		o.Parkingspotid,
	)
}

// Update uses an executor to update the Preferencespot
func (o *Preferencespot) Update(ctx context.Context, exec bob.Executor, s *PreferencespotSetter) error {
	return Preferencespots.Update(ctx, exec, s, o)
}

// Delete deletes a single Preferencespot record with an executor
func (o *Preferencespot) Delete(ctx context.Context, exec bob.Executor) error {
	return Preferencespots.Delete(ctx, exec, o)
}

// Reload refreshes the Preferencespot using the executor
func (o *Preferencespot) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Preferencespots.Query(
		ctx, exec,
		SelectWhere.Preferencespots.Userid.EQ(o.Userid),
		SelectWhere.Preferencespots.Parkingspotid.EQ(o.Parkingspotid),
	).One()
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

func (o PreferencespotSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals PreferencespotSetter) error {
	return Preferencespots.Update(ctx, exec, &vals, o...)
}

func (o PreferencespotSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	return Preferencespots.Delete(ctx, exec, o...)
}

func (o PreferencespotSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	var mods []bob.Mod[*dialect.SelectQuery]

	UseridPK := make([]int64, len(o))
	ParkingspotidPK := make([]int64, len(o))

	for i, o := range o {
		UseridPK[i] = o.Userid
		ParkingspotidPK[i] = o.Parkingspotid
	}

	mods = append(mods,
		SelectWhere.Preferencespots.Userid.In(UseridPK...),
		SelectWhere.Preferencespots.Parkingspotid.In(ParkingspotidPK...),
	)

	o2, err := Preferencespots.Query(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, old := range o {
		for _, new := range o2 {
			if new.Userid != old.Userid {
				continue
			}
			if new.Parkingspotid != old.Parkingspotid {
				continue
			}
			new.R = old.R
			*old = *new
			break
		}
	}

	return nil
}

func preferencespotsJoinParkingspotidParkingspot[Q dialect.Joinable](from preferencespotColumns, typ string) func(context.Context) modAs[Q, parkingspotColumns] {
	return func(ctx context.Context) modAs[Q, parkingspotColumns] {
		return modAs[Q, parkingspotColumns]{
			c: ParkingspotColumns,
			f: func(to parkingspotColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Parkingspots.Name(ctx).As(to.Alias())).On(
						to.Parkingspotid.EQ(from.Parkingspotid),
					))
				}

				return mods
			},
		}
	}
}

func preferencespotsJoinUseridUser[Q dialect.Joinable](from preferencespotColumns, typ string) func(context.Context) modAs[Q, userColumns] {
	return func(ctx context.Context) modAs[Q, userColumns] {
		return modAs[Q, userColumns]{
			c: UserColumns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name(ctx).As(to.Alias())).On(
						to.Userid.EQ(from.Userid),
					))
				}

				return mods
			},
		}
	}
}

// ParkingspotidParkingspot starts a query for related objects on parkingspot
func (o *Preferencespot) ParkingspotidParkingspot(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) ParkingspotsQuery {
	return Parkingspots.Query(ctx, exec, append(mods,
		sm.Where(ParkingspotColumns.Parkingspotid.EQ(psql.Arg(o.Parkingspotid))),
	)...)
}

func (os PreferencespotSlice) ParkingspotidParkingspot(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) ParkingspotsQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = psql.ArgGroup(o.Parkingspotid)
	}

	return Parkingspots.Query(ctx, exec, append(mods,
		sm.Where(psql.Group(ParkingspotColumns.Parkingspotid).In(PKArgs...)),
	)...)
}

// UseridUser starts a query for related objects on users
func (o *Preferencespot) UseridUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(ctx, exec, append(mods,
		sm.Where(UserColumns.Userid.EQ(psql.Arg(o.Userid))),
	)...)
}

func (os PreferencespotSlice) UseridUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = psql.ArgGroup(o.Userid)
	}

	return Users.Query(ctx, exec, append(mods,
		sm.Where(psql.Group(UserColumns.Userid).In(PKArgs...)),
	)...)
}

func (o *Preferencespot) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "ParkingspotidParkingspot":
		rel, ok := retrieved.(*Parkingspot)
		if !ok {
			return fmt.Errorf("preferencespot cannot load %T as %q", retrieved, name)
		}

		o.R.ParkingspotidParkingspot = rel

		return nil
	case "UseridUser":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("preferencespot cannot load %T as %q", retrieved, name)
		}

		o.R.UseridUser = rel

		return nil
	default:
		return fmt.Errorf("preferencespot has no relationship %q", name)
	}
}

func PreloadPreferencespotParkingspotidParkingspot(opts ...psql.PreloadOption) psql.Preloader {
	return psql.Preload[*Parkingspot, ParkingspotSlice](orm.Relationship{
		Name: "ParkingspotidParkingspot",
		Sides: []orm.RelSide{
			{
				From: "preferencespots",
				To:   TableNames.Parkingspots,
				ToExpr: func(ctx context.Context) bob.Expression {
					return Parkingspots.Name(ctx)
				},
				FromColumns: []string{
					ColumnNames.Preferencespots.Parkingspotid,
				},
				ToColumns: []string{
					ColumnNames.Parkingspots.Parkingspotid,
				},
			},
		},
	}, Parkingspots.Columns().Names(), opts...)
}

func ThenLoadPreferencespotParkingspotidParkingspot(queryMods ...bob.Mod[*dialect.SelectQuery]) psql.Loader {
	return psql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadPreferencespotParkingspotidParkingspot(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load PreferencespotParkingspotidParkingspot", retrieved)
		}

		err := loader.LoadPreferencespotParkingspotidParkingspot(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadPreferencespotParkingspotidParkingspot loads the preferencespot's ParkingspotidParkingspot into the .R struct
func (o *Preferencespot) LoadPreferencespotParkingspotidParkingspot(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.ParkingspotidParkingspot = nil

	related, err := o.ParkingspotidParkingspot(ctx, exec, mods...).One()
	if err != nil {
		return err
	}

	o.R.ParkingspotidParkingspot = related
	return nil
}

// LoadPreferencespotParkingspotidParkingspot loads the preferencespot's ParkingspotidParkingspot into the .R struct
func (os PreferencespotSlice) LoadPreferencespotParkingspotidParkingspot(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	parkingspots, err := os.ParkingspotidParkingspot(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range parkingspots {
			if o.Parkingspotid != rel.Parkingspotid {
				continue
			}

			o.R.ParkingspotidParkingspot = rel
			break
		}
	}

	return nil
}

func PreloadPreferencespotUseridUser(opts ...psql.PreloadOption) psql.Preloader {
	return psql.Preload[*User, UserSlice](orm.Relationship{
		Name: "UseridUser",
		Sides: []orm.RelSide{
			{
				From: "preferencespots",
				To:   TableNames.Users,
				ToExpr: func(ctx context.Context) bob.Expression {
					return Users.Name(ctx)
				},
				FromColumns: []string{
					ColumnNames.Preferencespots.Userid,
				},
				ToColumns: []string{
					ColumnNames.Users.Userid,
				},
			},
		},
	}, Users.Columns().Names(), opts...)
}

func ThenLoadPreferencespotUseridUser(queryMods ...bob.Mod[*dialect.SelectQuery]) psql.Loader {
	return psql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadPreferencespotUseridUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load PreferencespotUseridUser", retrieved)
		}

		err := loader.LoadPreferencespotUseridUser(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadPreferencespotUseridUser loads the preferencespot's UseridUser into the .R struct
func (o *Preferencespot) LoadPreferencespotUseridUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.UseridUser = nil

	related, err := o.UseridUser(ctx, exec, mods...).One()
	if err != nil {
		return err
	}

	o.R.UseridUser = related
	return nil
}

// LoadPreferencespotUseridUser loads the preferencespot's UseridUser into the .R struct
func (os PreferencespotSlice) LoadPreferencespotUseridUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.UseridUser(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range users {
			if o.Userid != rel.Userid {
				continue
			}

			o.R.UseridUser = rel
			break
		}
	}

	return nil
}

func attachPreferencespotParkingspotidParkingspot0(ctx context.Context, exec bob.Executor, count int, preferencespot0 *Preferencespot, parkingspot1 *Parkingspot) (*Preferencespot, error) {
	setter := &PreferencespotSetter{
		Parkingspotid: omit.From(parkingspot1.Parkingspotid),
	}

	err := Preferencespots.Update(ctx, exec, setter, preferencespot0)
	if err != nil {
		return nil, fmt.Errorf("attachPreferencespotParkingspotidParkingspot0: %w", err)
	}

	return preferencespot0, nil
}

func (preferencespot0 *Preferencespot) InsertParkingspotidParkingspot(ctx context.Context, exec bob.Executor, related *ParkingspotSetter) error {
	parkingspot1, err := Parkingspots.Insert(ctx, exec, related)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachPreferencespotParkingspotidParkingspot0(ctx, exec, 1, preferencespot0, parkingspot1)
	if err != nil {
		return err
	}

	preferencespot0.R.ParkingspotidParkingspot = parkingspot1

	return nil
}

func (preferencespot0 *Preferencespot) AttachParkingspotidParkingspot(ctx context.Context, exec bob.Executor, parkingspot1 *Parkingspot) error {
	var err error

	_, err = attachPreferencespotParkingspotidParkingspot0(ctx, exec, 1, preferencespot0, parkingspot1)
	if err != nil {
		return err
	}

	preferencespot0.R.ParkingspotidParkingspot = parkingspot1

	return nil
}

func attachPreferencespotUseridUser0(ctx context.Context, exec bob.Executor, count int, preferencespot0 *Preferencespot, user1 *User) (*Preferencespot, error) {
	setter := &PreferencespotSetter{
		Userid: omit.From(user1.Userid),
	}

	err := Preferencespots.Update(ctx, exec, setter, preferencespot0)
	if err != nil {
		return nil, fmt.Errorf("attachPreferencespotUseridUser0: %w", err)
	}

	return preferencespot0, nil
}

func (preferencespot0 *Preferencespot) InsertUseridUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	user1, err := Users.Insert(ctx, exec, related)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachPreferencespotUseridUser0(ctx, exec, 1, preferencespot0, user1)
	if err != nil {
		return err
	}

	preferencespot0.R.UseridUser = user1

	return nil
}

func (preferencespot0 *Preferencespot) AttachUseridUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachPreferencespotUseridUser0(ctx, exec, 1, preferencespot0, user1)
	if err != nil {
		return err
	}

	preferencespot0.R.UseridUser = user1

	return nil
}
