-- Booking details
CREATE TABLE IF NOT EXISTS Booking (
  BookingId BIGSERIAL PRIMARY KEY,
  BookingUUID UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
  UserId BIGINT NOT NULL REFERENCES Users(UserId),
  ParkingSpotId BIGINT NOT NULL REFERENCES ParkingSpot(ParkingSpotId),
  CarId BIGINT NOT NULL REFERENCES Car(CarId),
  PaidAmount DECIMAL NOT NULL,
  CreatedAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS BookingUUIDIdx ON Booking(BookingUUID);