CREATE TABLE IF NOT EXISTS ResetToken (
    TokenID SERIAL PRIMARY KEY,
    Token TEXT NOT NULL,
    AuthUUID UUID UNIQUE NOT NULL REFERENCES Auth(AuthUUID),
    CreatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW()
);