-- Car details
CREATE TABLE IF NOT EXISTS Car (
  CarId BIGSERIAL PRIMARY KEY NOT NULL,
  UserId BIGINT NOT NULL REFERENCES Users(UserId),
  CarUUID UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  LicensePlate TEXT NOT NULL,
  Make TEXT NOT NULL,
  Model TEXT NOT NULL,
  Color TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS CarUUIDIdx ON Car(CarUUID);
