-- User details
CREATE TABLE IF NOT EXISTS Users (
  UserID BIGSERIAL PRIMARY KEY NOT NULL,
  UserUUID UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
  AuthUUID UUID UNIQUE NOT NULL REFERENCES Auth(AuthUUID),
  FullName TEXT NOT NULL,
  Email TEXT NOT NULL,
  IsVerified BOOLEAN NOT NULL DEFAULT false,
  AddedAt TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS UserUUIDs ON Users (UserUUID);