name: Backend load test CI

on:
  merge_group:

concurrency:
  # Makes sure only one is run per PR
  group: backend-load-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    continue-on-error: true # Errors here should not crash the job
    name: Check backend/k6 for changes
    outputs:
      exists: ${{ steps.changed.outputs.exists }}
    runs-on: ubuntu-latest

    steps:
      - id: changed
        uses: yumemi-inc/changed-files@v3
        with:
          patterns: |
            .github/workflows/backend-load.yaml
            k6/**
            backend/**
            !backend/docs/**
            !backend/README.md

  loadtest:
    needs: [changes]
    name: Backend load testing
    if: needs.changes.outputs.exists != 'false'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            backend
            k6

      - run: |
          cp example.env .env
          docker compose up -d --build
        working-directory: backend

      - uses: grafana/setup-k6-action@v1

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: npm ci
        working-directory: k6

      - run: npm run build
        working-directory: k6

      - uses: grafana/run-k6-action@v1
        with:
          path: |
            ./k6/dist/*.js
