name: Backend CI

on:
  - pull_request
  - merge_group

concurrency:
  # Makes sure only one is run per PR
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    continue-on-error: true # Errors here should not crash the job
    name: Check backend for changes
    outputs:
      exists: ${{ steps.changed.outputs.exists }}
    runs-on: ubuntu-latest

    steps:
      - id: changed
        uses: yumemi-inc/changed-files@v3
        with:
          patterns: |
            .github/workflows/backend.yaml
            backend/**
            !backend/docs/**
            !backend/README.md

  lint:
    needs: [changes]
    if: needs.changes.outputs.exists != 'false'

    name: Backend lint checks
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: backend

      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: |
            backend/go.sum

      - uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: backend

  test:
    needs: [changes]
    if: needs.changes.outputs.exists != 'false'

    name: Backend tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: backend

      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: |
            backend/go.sum

      - run: go test ./...
        working-directory: backend

  build:
    needs: [changes]
    if: needs.changes.outputs.exists != 'false'

    name: Backend container build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: backend

      - run: podman build -t packserver backend/
