name: Backend CD

on:
  push:
    branches:
      - main
    tags:
      - releases/**
    paths:
      - backend/**/*

concurrency:
  group: backend-deploy-${{ github.ref }}
  cancel-in-progress: true # only deploy latest

jobs:
  container-build:
    name: Build and push backend container
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: backend

      - name: Get Git commit timestamps
        run: echo "TIMESTAMP=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Setup BuildKit
        uses: docker/setup-buildx-action@v3

      - name: Generate metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/parkwithease/parkserver
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: backend
          file: backend/Containerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}

  deploy:
    needs:
      - container-build

    name: Deploy backend
    runs-on: ubuntu-latest

    environment:
      name: ${{ (github.ref_type == 'branch' && 'backend-staging') || 'backend-production' }}
      url: ${{ env.DEPLOYMENT_TARGET }}

    steps:
      - name: Trigger deployment
        run: curl "$DEPLOY_URL"
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
